#!/bin/bash

# Function to display help
show_help() {
    echo "Usage: $0 [options] [tasks...]"
    echo ""
    echo "Options:"
    echo "  -h, --help             		Show this help message"
    echo "  -o, -y, --ontem, --yesterday        Use yesterday's date and change 'hoje' to 'ontem'"
    echo "  -n, --nome, --name  NAME             Change the name permanently (default: 'Your Name')"
    echo "  -p, --problema, --problem  TEXT     Change the problem description (default: 'Não')"
    echo "  -t, --tag  SPACES                   Set the number of whitespaces before the bullet point (default: 4)"
    echo ""
    echo "Tasks are the activities you want to list for the day."
}

# Check if xclip is installed
if ! command -v xclip &> /dev/null; then
    echo "xclip could not be found, please install it to use this script."
    exit 1
fi

# Default values
FILE_NAME=$0
DATE_OPTION="hoje"
DATE_FORMAT="%d/%m"
NAME="Your Name"
PROBLEM="Não"
WHITESPACE_COUNT=4

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) 
            show_help
            exit 0
            ;;
        -o|-y|--yesterday|--ontem)
            DATE_OPTION="ontem"
            ;;
        -n|--name|--nome)
            if [[ -n "$2" ]]; then
                NAME=$2
                sudo sed -i "s/NAME=\"[^\"]*\"/NAME=\"$2\"/" "$FILE_NAME"
                shift
            else
                echo "Error: --nome requires a non-empty option argument."
                show_help
                exit 1
            fi
            ;;
        -p|--problem|--problema)
            if [[ -n "$2" ]]; then
                PROBLEM="$2"
                shift
            else
                echo "Error: --problema requires a non-empty option argument."
                show_help
                exit 1
            fi
            ;;
        -t|--tag)
            if [[ -n "$2" && "$2" =~ ^[0-9]+$ ]]; then
                WHITESPACE_COUNT=4$2
                sudo sed -i "s/WHITESPACE_COUNT=4[0-9]*/WHITESPACE_COUNT=$2/" "$FILE_NAME"
                shift
            else
                echo "Error: --tag requires a non-empty numeric option argument."
                show_help
                exit 1
            fi
            ;;
        *) 
            TASKS+=("$1")
            ;;
    esac
    shift
done

# Determine the date
if [[ "$DATE_OPTION" == "ontem" ]]; then
    DATE=$(date -d "yesterday" +"$DATE_FORMAT")
    TODAY_WORD="ontem"
else
    DATE=$(date +"$DATE_FORMAT")
    TODAY_WORD="hoje"
fi

# Build the task list
TEXT=""
SPACES=$(printf '%*s' "$WHITESPACE_COUNT" '' | tr ' ' ' ')
for task in "${TASKS[@]}"; do
    TEXT+="$SPACES• $task\n"
done

# Create the final output
OUTPUT="Daily $DATE
Nome: $NAME

*O que fiz/vou fazer $TODAY_WORD?*
$TEXT
*Estou com problema em algo?*
$SPACES• $PROBLEM"

# Copy the output to clipboard
echo -e "$OUTPUT" | xclip -selection clipboard

echo "Copied."

